[project]
name = "pichat"
version = "0.1.0"
description = ""
readme = "readme.md"

dependencies = [
    "requests",
    "flask",
    "flask-socketio",
    "flask-cors",
    "dotenv",
    "yfinance",
    "yt-dlp",
    "gunicorn",
    "apscheduler"
]

[project.optional-dependencies]
test = [
    "pytest>=8.0",
    "pytest-asyncio>=0.24",
    "websockets"
]


[project.scripts]
pichat = "main:main"